### ################ ###
### Global Variables ###
### ################ ###

global:
  platform: "k8s"
  enforcer:
    enabled: true
  gateway:
    # change address to gateway endpoint
    address: <SaaS-Gateway-Endpoint>-gw.cloud.aquasec.com # POV to Update. E.g. cxxx651191-gw.cloud.aquasec.com
    port: 443 # 443 for SaaS // 8443 for self-hosted
  # Specifies the secret data for imagePullSecrets needed to fetch the private docker images
  imageCredentials:
    create: true
    name: "aqua-registry"
    repositoryUriPrefix: "registry.aquasec.com" # for dockerhub - "docker.io"
    registry: "registry.aquasec.com" #REQUIRED only if create is true, for dockerhub - "index.docker.io/v1/"
    username: "" # POV to Update. E.g. user@aquasec.com
    password: "" # POV to Update

serviceAccount:
  create: true



### ############# ###
### Kube Enforcer ###
### ############# ###

# Kube-Enforcer Image
image:
  repository: "kube-enforcer"
  tag: "2022.4"
  pullPolicy: Always

# Display a custom cluster name in the infrastructure tab of Aqua Enterprise
clusterName: "Default-cluster-name" # POV to Update. E.g. AWS-Bottlerocket-Cluster-1

certsSecret:
  autoGenerate: true

aquaSecret:
  create: true
  name: "aqua-kube-enforcer-token"
  # Enter the enforcer token in "clear-text" format without quotes generated from the Console UI #
  kubeEnforcerToken: ke-token-cleartext-noquotes # POV to Update. E.g. 2af8dbb2-f1a2-4212-b343-5f8cfce93a5e

resources: {}
  # Note: For recommendations please check the official sizing guide.
  # requests:
  #   cpu: 250m
  #   memory: 0.2Gi
  # limits:
  #   cpu: 500m
  #   memory: 1.5Gi
  
  

### ############# ###
### Aqua Enforcer ###
### ############# ###

enforcer:
  # Enter the enforcer token in "clear-text" format without quotes generated from the Console UI #
  enforcerToken: enforcer-token-cleartext-noquotes # POV to Update. E.g. 2af8dbb2-f1a2-4212-b343-5f8cfce93a5e
  expressMode: true

  # Required for AWS Bottlerocket --> privileged mode and SELinux 
  securityContext:
    privileged: true
    seLinuxOptions:
      user: system_u
      role: system_r
      type: super_t
      level: s0
    capabilities:
      add:
        - SYS_ADMIN
        - NET_ADMIN
        - NET_RAW
        - SYS_PTRACE
        - KILL
        - MKNOD
        - SETGID
        - SETUID
        - SYS_MODULE
        - AUDIT_CONTROL
        - SYSLOG
        - SYS_CHROOT
        - SYS_RESOURCE
        - IPC_LOCK

  image:
    repository: enforcer
    tag: "2022.4"
    pullPolicy: Always
    
  resources: { }
    # Note: For recommendations please check the official sizing guide.
    # requests:
    #   cpu: 350m
    #   memory: 0.512Gi
    # limits:
    #   cpu: 1500m
    #   memory: 1.5Gi
